// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web platform is not supported for this app.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU3FxqsSL0qHXFxlYCZ_j1kPXV0jKOB3g',
    appId: '1:369381806316:android:c100593511e0ae748415c9',
    messagingSenderId: '369381806316',
    projectId: 'marketplace-2065',
    storageBucket: 'marketplace-2065.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZx5iKvBfF39xh9PhINCLF6IABjx9c6o',
    appId: '1:369381806316:ios:e711dd0a71bffafa8415c9',
    messagingSenderId: '369381806316',
    projectId: 'marketplace-2065',
    storageBucket: 'marketplace-2065.firebasestorage.app',
    androidClientId:
        '369381806316-crmtqk8nv939q7qpi3nteb2dthej5omg.apps.googleusercontent.com',
    iosClientId:
        '369381806316-8nvekfm5n9h5kjaclfj4f12pq3n3colf.apps.googleusercontent.com',
    iosBundleId: 'marketplace.shop.marketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZx5iKvBfF39xh9PhINCLF6IABjx9c6o',
    appId: '1:369381806316:ios:e711dd0a71bffafa8415c9',
    messagingSenderId: '369381806316',
    projectId: 'marketplace-2065',
    storageBucket: 'marketplace-2065.firebasestorage.app',
    androidClientId:
        '369381806316-crmtqk8nv939q7qpi3nteb2dthej5omg.apps.googleusercontent.com',
    iosClientId:
        '369381806316-8nvekfm5n9h5kjaclfj4f12pq3n3colf.apps.googleusercontent.com',
    iosBundleId: 'marketplace.shop.marketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd_GZzm5iMm6Cj3F077PP0JjlHiAiOYyQ',
    appId: '1:369381806316:web:b70c34630211abf98415c9',
    messagingSenderId: '369381806316',
    projectId: 'marketplace-2065',
    authDomain: 'marketplace-2065.firebaseapp.com',
    storageBucket: 'marketplace-2065.firebasestorage.app',
    measurementId: 'G-0ND7YC9D8Q',
  );
}
